apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name}}-headless-service
spec:
  selector:
    app: {{ .Values.metadata.name}}
  ports:
  - port:  {{ .Values.database.port}}
    targetPort: {{ .Values.database.port}}
