apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.metadata.name }}-claim
spec:
  storageClassName: {{.Values.volumeClaim.storageclass}} 
  resources:
    requests:
      storage: {{ .Values.volumeClaim.storagesize}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
